### ISSUE TITLE
Not working on iPhone ()

### ISSUE THREAD

**Issue by soulmecca** [mateusc42/react-native-firebase-mlkit#1]
Hi,
Thanks for this great repository. 
I tried to implement this but failed.
What I did was like this:
1. react-native init testApp
2. cd testApp
3. npm install react-native-firebase-mlkit --save
4. react-native link react-native-firebase-mlkit
5. Added GoogleService-Info.plist into /ios/
6. pod init
7. added  
     pod 'Firebase/Core'
     pod 'Firebase/MLVision'
     pod 'Firebase/MLVisionTextModel'
    into Podfile
8. pod install 
9. open xcworkspace file with xcode (tried both 10 and 9)
10. build

Then I got this error:

<img width="844" alt="screen shot 2018-08-31 at 3 33 38 pm" src="https://user-images.githubusercontent.com/873501/44932475-891b3880-ad33-11e8-91b1-8587d636b2c0.png">

Do you know what I have done wrong?

Thanks!

**Comment by mateuscardosogs** [comment]
Hello man, I could not test the iOS part of the application and did not realize the error, but I made the adjustments and now the package is working correctly for both platforms in the latest version. Try to upgrade.
