### ISSUE TITLE
Question: plan to support custom models?

### ISSUE THREAD

**Issue by GaspardC** [mateusc42/react-native-firebase-mlkit#3]
Hello,
First thanks for your repo.
Are you planning to add support for custom models?

**Comment by gianpaj** [comment]
same question 😊

For Android, for example, I believe we need to add this code and expose some parameters for the Model
https://firebase.google.com/docs/ml-kit/android/use-custom-models?authuser=0#make_models_available_locally

**Comment by mateuscardosogs** [comment]
Yes, I do. but unfortunately I have not got the time to encode this new feature yet.
