### ISSUE TITLE
Barcodes?

### ISSUE THREAD

**Issue by ctoLarsson** [mateusc42/react-native-firebase-mlkit#5]
Great initiative setting this up.

Does this code support the vision elements like Barcode? I looked into the code and I see only the text function. Can it be easily extended with the other functions like faces, barcodes etc?

https://firebase.google.com/docs/ml-kit/read-barcodes

If not, what would be the best way to bridge to a native code to call Firebase ML Kit?

**Comment by mateuscardosogs** [comment]
At the moment the library does not support bar codes, if you wanted to add this feature would have to implement in the native code with a new function to request the qr code. If you want to add this new feature, we would be creating a pull request.
